export const fillHoverColor = '#346B4F';
export const selectedFillColor = '#71AF7E';

export const visualisationsKey = [
  {
    index: 0,
    dataName: 'cancelPublicEvents',
    formatName: 'Cancel Public Events',
    thresholds: [0, 1, 2,],
    thresholdNames: [" = No Measures", "= Recommend Cancelling", "= Require Cancelling", "= No Data"],
    colours: ['#d2e4f7', '#B9D1E9', '#5F96CC', '#bdbdbd',],
  },
  {
    index: 1,
    dataName: 'closePublicTransport',
    formatName: 'Close Public Transport',
    thresholds: [0, 1, 2,],
    thresholdNames: [" = No Measures", "= Recommend Cancelling", "= Require Cancelling", "= No Data"],
    colours: ['#d2e4f7', '#B9D1E9', '#5F96CC', '#bdbdbd',],
  },
  {
    index: 2,
    dataName: 'confirmedCases',
    formatName: 'Confirmed Cases',
    thresholds: [0, 1000, 100000, 100000, 1000000, 100000000],
    thresholdNames: ['= 0', '<= 1000', '<= 100,000', '<= 1,000,000', '<= 100,000,000',],
    colours: ['#d2e4f7', '#B9D1E9', '#5F96CC', '#0455A4', '#0e4c87', '#043A6E'],
  },
  {
    index: 3,
    dataName: 'confirmedDeaths',
    formatName: 'Confirmed Deaths',
    thresholds: [0, 1000, 100000, 1000000, 10000000],
    thresholdNames: ['= 0', '<= 1000', '<= 100,000', '<= 1,000,000', '<= 10,000,000'],
    colours: ['#d2e4f7', '#B9D1E9', '#5F96CC', '#0455A4', '#043A6E',],
  },
  {
    index: 4,
    dataName: 'contactTracing',
    formatName: 'Contact Tracing',
    thresholds: [0, 1, 2],
    thresholdNames: ["= No Contact Tracing", "= Limited Contact Tracing", "= Full Contact Tracing"],
    colours: ['#d2e4f7', '#B9D1E9', '#5F96CC',],
  },
  {
    index: 5,
    dataName: 'facialCovering',
    formatName: 'Facial Covering',
    thresholds: [0, 1, 2, 3, 4,],
    thresholdNames: ["= No policy", "= Recommended", "= Required in Some Spaces", "= Required in All Spaces", "= Required Outside the Home"],
    colours: ['#d2e4f7', '#B9D1E9', '#5F96CC', '#0455A4', '#043A6E',],
  },
  {
    index: 6,
    dataName: 'gatheringRestrictions',
    formatName: 'Gathering Restrictions',
    thresholds: [0, 1, 2, 3, 4],
    thresholdNames: ["= No Restrictions", "= Restrictions on 1000+", "= Restrictions on 100+", "= Restrictions on 10+",  "= Restrictions on All", "= No Data"],
    colours: ['#d2e4f7', '#B9D1E9', '#5F96CC', '#0455A4', '#043A6E', '#bdbdbd'],
  },
  {
    index: 7,
    dataName: 'internalMovementRestrictions',
    formatName: 'Internal Movement Restrictions',
    thresholds: [0, 1, 2,],
    thresholdNames: ["= No Measures", "= Recommended Not to Travel", "= Internal Travel Restrictions", "= No Data"],
    colours: ['#d2e4f7', '#B9D1E9', '#5F96CC', '#bdbdbd'],
  },
  {
    index: 8,
    dataName: 'internationalTravelControls',
    formatName: 'International Travel',
    thresholds: [0, 1, 2, 3, 4,],
    thresholdNames: ["= No Restrictions", "= Screening Arrivals", "= Quarantine Arrivals", "= Ban from Some Regions", "= Total Border Closure",],
    colours: ['#d2e4f7', '#B9D1E9', '#5F96CC', '#0455A4', '#043A6E', '#bdbdbd'],
  },
  {
    index: 9,
    dataName: 'populationVaccinated',
    formatName: 'Population Vaccinated',
    thresholds: [0, 20, 40, 60, 80, 100],
    thresholdNames: ["= 0-20% Vaccinated", "= 21-40% Vaccinated", "= 41-60% Vaccinated", "= 61-80% Vaccinated", "= 81-100% Vaccinated",],
    colours: ['#d2e4f7', '#B9D1E9', '#5F96CC', '#0455A4', '#043A6E', '#bdbdbd'],
  },
  {
    index: 10,
    dataName: 'publicInfoCampaigns',
    formatName: 'Public Info Campaigns',
    thresholds: [0, 1, 2],
    thresholdNames: ["= No Campaigns", "= Officials Urging Caution", "= Coordinated Public Campaign", "= No Data"],
    colours: ['#d2e4f7', '#B9D1E9', '#5F96CC', '#bdbdbd'],
  },
  {
    index: 11,
    dataName: 'schoolClosing',
    formatName: 'School Closing',
    thresholds: [0, 1, 2, 3],
    thresholdNames: ["= No Measures", "= Recommended Closing", "= Require Closing for Some", "= Require Closing on All Levels", "= No Data"],
    colours: ['#d2e4f7', '#B9D1E9', '#5F96CC', '#0455A4', '#bdbdbd'],
  },
  {
    index: 12,
    dataName: 'testingPolicy',
    formatName: 'Testing Policy',
    thresholds: [0, 1, 2, 3],
    thresholdNames: ["= No Testing Policy", "= Only Critical Workers", "= Only Symptoms", "= Open Public Testing", "= No Data"],
    colours: ['#d2e4f7', '#B9D1E9', '#5F96CC', '#0455A4', '#bdbdbd'],
  },
  {
    index: 13,
    dataName: 'vaccinationPolicy',
    formatName: 'Vaccination Policy',
    thresholds: [0, 1, 2, 3, 4, 5],
    thresholdNames: ["= No Availability", "= Availability for One", "= Availability for Two", "= Availability for Three", "= Universal Availability"],
    colours: ['#d2e4f7', '#B9D1E9', '#5F96CC', '#0455A4', '#043A6E', '#043A6E'],
  },
  {
    index: 14,
    dataName: 'workplaceClosing',
    formatName: 'Workplace Closing',
    thresholds: [0, 1, 2, 3],
    thresholdNames: ["= No Measures", "= Recommended Closing", "= Some Required Closing", "= All Required Closing", "= No Data"],
    colours: ['#d2e4f7', '#B9D1E9', '#5F96CC', '#0455A4', '#bdbdbd'],
  }
];




export const timelineItems = [
    {
      year: '2020',
      yearShown: true,
      date: 'Jan',
      dataName: '20200101',
      dataIndex: 0,
    },
    {
      year: '2020',
      yearShown: false,
      date: 'Feb',
      dataName: '20200201',
      dataIndex: 1,
    },
    {
      year: '2020',
      yearShown: false,
      date: 'Mar',
      dataName: '20200301',
      dataIndex: 2,
    },
    {
      year: '2020',
      yearShown: false,
      date: 'Apr',
      dataName: '20200401',
      dataIndex: 3,
    },
    {
      year: '2020',
      yearShown: false,
      date: 'May',
      dataName: '20200501',
      dataIndex: 4,
    },
    {
      year: '2020',
      yearShown: false,
      date: 'Jun',
      dataName: '20200601',
      dataIndex: 5,
    },
    {
      year: '2020',
      yearShown: false,
      date: 'Jul',
      dataName: '20200701',
      dataIndex: 6,
    },
    {
      year: '2020',
      yearShown: false,
      date: 'Aug',
      dataName: '20200801',
      dataIndex: 7,
    },
    {
      year: '2020',
      yearShown: false,
      date: 'Sep',
      dataName: '20200901',
      dataIndex: 8,
    },
    {
      year: '2020',
      yearShown: false,
      date: 'Oct',
      dataName: '20201001',
      dataIndex: 9,
    },
    {
      year: '2020',
      yearShown: false,
      date: 'Nov',
      dataName: '20201101',
      dataIndex: 10,
    },
    {
      year: '2020',
      yearShown: false,
      date: 'Dec',
      dataName: '20201201',
      dataIndex: 11,
    },
    {
      year: '2021',
      yearShown: true,
      date: 'Jan',
      dataName: '20210101',
      dataIndex: 12,
    },
    {
        year: '2021',
        yearShown: false,
        date: 'Feb',
        dataName: '20210201',
        dataIndex: 13,
      },
      {
        year: '2021',
        yearShown: false,
        date: 'Mar',
        dataName: '20210301',
        dataIndex: 14,
      },
      {
        year: '2021',
        yearShown: false,
        date: 'Apr',
        dataName: '20210401',
        dataIndex: 15,
      },
      {
        year: '2021',
        yearShown: false,
        date: 'May',
        dataName: '20210501',
        dataIndex: 16,
      },
      {
        year: '2021',
        yearShown: false,
        date: 'Jun',
        dataName: '20210601',
        dataIndex: 17,
      },
      {
        year: '2021',
        yearShown: false,
        date: 'Jul',
        dataName: '20210701',
        dataIndex: 18,
      },
      {
        year: '2021',
        yearShown: false,
        date: 'Aug',
        dataName: '20210801',
        dataIndex: 19,
      },
      {
        year: '2021',
        yearShown: false,
        date: 'Sep',
        dataName: '20210901',
        dataIndex: 20,
      },
      {
        year: '2021',
        yearShown: false,
        date: 'Oct',
        dataName: '20211001',
        dataIndex: 21,
      },
      {
        year: '2021',
        yearShown: false,
        date: 'Nov',
        dataName: '20211101',
        dataIndex: 22,
      },
      {
        year: '2021',
        yearShown: false,
        date: 'Dec',
        dataName: '20211201',
        dataIndex: 23,
      },
      {  year: '2022',
      yearShown: true,
      date: 'Jan',
      dataName: '20220101',
      dataIndex: 24,
    },
    {
        year: '2022',
        yearShown: false,
        date: 'Feb',
        dataName: '20220201',
        dataIndex: 25,
      },
      {
        year: '2022',
        yearShown: false,
        date: 'Mar',
        dataName: '20220301',
        dataIndex: 26,
      },
      {
        year: '2022',
        yearShown: false,
        date: 'Apr',
        dataName: '20220401',
        dataIndex: 27,
      },
      {
        year: '2022',
        yearShown: false,
        date: 'May',
        dataName: '20220501',
        dataIndex: 28,
      },
      {
        year: '2022',
        yearShown: false,
        date: 'Jun',
        dataName: '20220601',
        dataIndex: 29,
      },
      {
        year: '2022',
        yearShown: false,
        date: 'Jul',
        dataName: '20220701',
        dataIndex: 30,
      },
      {
        year: '2022',
        yearShown: false,
        date: 'Aug',
        dataName: '20220801',
        dataIndex: 31,
      },
      {
        year: '2022',
        yearShown: false,
        date: 'Sep',
        dataName: '20220901',
        dataIndex: 32,
      },
      {
        year: '2022',
        yearShown: false,
        date: 'Oct',
        dataName: '20221001',
        dataIndex: 33,
      },
      {
        year: '2022',
        yearShown: false,
        date: 'Nov',
        dataName: '20221101',
        dataIndex: 34,
      },
      {
        year: '2022',
        yearShown: false,
        date: 'Dec',
        dataName: '20221201',
        dataIndex: 35,
      },
      {
        year: '2023',
        yearShown: true,
        date: 'Jan',
        dataName: '20221201',
        dataIndex: 35,
      },
  ];

  // Thresholds from: https://github.com/OxCGRT/covid-policy-dataset/blob/main/documentation_and_codebook.md 
  
  export default timelineItems;